name: Pylint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]  # 3 jobs in the matrix

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If you have a requirements.txt, uncomment the next line:
          # pip install -r requirements.txt
          pip install pylint

      - name: Run Pylint with threshold
        # fail the job if score < 8.0
        run: |
          set -e
          # Only lint tracked Python files
          FILES="$(git ls-files '*.py')"
          if [ -z "$FILES" ]; then
            echo "No Python files to lint."
            exit 0
          fi
          pylint --fail-under=8.0 $FILES
